# Generated by Django 4.1.1 on 2023-03-16 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learningDirections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("send_date", models.DateField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
                "ordering": ["student", "send_date", "parameter"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Дата"),
                ),
                (
                    "template",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Шаблон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лист обратной связи",
                "verbose_name_plural": "Листы обратной связи",
                "ordering": ["date", "responsible"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Критерий")),
                (
                    "learning_direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learningDirections.learningdirection",
                        verbose_name="Направление обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр обратной связи",
                "verbose_name_plural": "Параметры обратной связи",
                "ordering": ["learning_direction", "name"],
            },
        ),
    ]
