# Generated by Django 4.1.1 on 2023-04-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_alter_lesson_learning_group_alter_student_avatar"),
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_list",
        ),
        migrations.CreateModel(
            name="FeedbackGroupList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="feedback.feedback",
                        verbose_name="Обратная связь",
                    ),
                ),
                (
                    "feedback_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="feedback.feedbacklist",
                        verbose_name="Общий список ОС",
                    ),
                ),
                (
                    "learning_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_group_list",
                        to="groups.learninggroup",
                        verbose_name="Обратная связь по группе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список по группе",
                "verbose_name_plural": "Списки по группам",
                "ordering": ["learning_group"],
            },
        ),
    ]
