# Generated by Django 4.1.1 on 2023-04-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learningDirections", "0004_alter_syllabus_learning_direction_and_more"),
        ("feedback", "0003_remove_feedback_feedback_list_feedbackgrouplist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackparam",
            name="learning_direction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_params",
                to="learningDirections.learningdirection",
                verbose_name="Направление обучения",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackparam",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Критерий"),
        ),
    ]
