# Generated by Django 4.1.1 on 2023-04-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_alter_lesson_learning_group_alter_student_avatar"),
        ("learningDirections", "0004_alter_syllabus_learning_direction_and_more"),
        ("feedback", "0005_remove_feedbackgrouplist_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback_group_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="feedback.feedbackgrouplist",
                verbose_name="Лист ОС группы",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="groups.student",
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackgrouplist",
            name="feedback_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_group_list",
                to="feedback.feedbacklist",
                verbose_name="Общий список ОС",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedbackgrouplist",
            name="learning_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_group_list",
                to="groups.learninggroup",
                verbose_name="Обратная связь по группе",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedbackparam",
            name="learning_direction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_params",
                to="learningDirections.learningdirection",
                verbose_name="Направление обучения",
            ),
            preserve_default=False,
        ),
    ]
