# Generated by Django 4.1.1 on 2023-04-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_alter_feedback_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "feedback_student_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_report",
                        to="feedback.feedbackstudentlist",
                        verbose_name="Лист ОС ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Генерируемый отчет",
                "verbose_name_plural": "Генерируемые отчеты",
                "ordering": ["feedback_student_list"],
            },
        ),
    ]
