# Generated by Django 4.1.1 on 2023-04-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_generatedreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedreport",
            name="feedback_student_list",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_report",
                to="feedback.feedbackstudentlist",
                verbose_name="Лист ОС ученика",
            ),
        ),
    ]
