# Generated by Django 4.1.1 on 2023-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="learningGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("studyCourse", models.IntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("firstLesson", models.DateTimeField(auto_now=True)),
                ("dayOfLessons", models.ManyToManyField(to="groups.lessondays")),
            ],
        ),
    ]
