# Generated by Django 4.1.1 on 2022-10-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learningDirections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="learningGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("dayOfLessons", models.CharField(max_length=50)),
                ("studyCourse", models.IntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=30)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="learningDirections.learningdirection",
                    ),
                ),
            ],
        ),
    ]
