# Generated by Django 4.1.1 on 2023-02-25 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learninggroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="students", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="learninggroup",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
