# Generated by Django 4.1.1 on 2022-10-24 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninggroup",
            name="firstLesson",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="learninggroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
