# Generated by Django 4.1.1 on 2023-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="learning_group",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="students",
                to="groups.learninggroup",
                verbose_name="Учебные группы",
            ),
        ),
    ]
