# Generated by Django 4.1.1 on 2022-10-24 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0003_learninggroup_firstlesson_learninggroup_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learninggroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
