# Generated by Django 4.1.1 on 2022-11-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_learninggroup_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learninggroup",
            name="direction",
        ),
    ]
