# Generated by Django 4.1.1 on 2023-03-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_student_birthday_alter_student_learning_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentlessonstatus",
            options={
                "ordering": ["lesson"],
                "verbose_name": "Статус посещения урока",
                "verbose_name_plural": "Статистика посещения уроков",
            },
        ),
        migrations.AlterField(
            model_name="studentlessonstatus",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_lesson_status",
                to="groups.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
