# Generated by Django 4.1.1 on 2023-03-27 12:38

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_alter_learninggroup_learning_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.ImageField(null=True, upload_to=groups.models.make_path),
        ),
    ]
