# Generated by Django 4.1.1 on 2023-03-27 13:27

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_student_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=groups.models.make_path
            ),
        ),
    ]
