# Generated by Django 4.1.1 on 2023-04-17 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0009_alter_lesson_learning_group_alter_student_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninggroup",
            name="curator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curator_group",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Куратор группы",
            ),
        ),
        migrations.AlterField(
            model_name="learninggroup",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_group",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
    ]
