# Generated by Django 4.1.1 on 2023-04-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0012_studentcomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcomments",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.student",
                verbose_name="Ученик",
            ),
        ),
    ]
