# Generated by Django 4.1.1 on 2022-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(blank=True, default="Не указано", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="Не указано", max_length=255),
        ),
    ]
