# Generated by Django 4.1.1 on 2022-10-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_lastname_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userType",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.usertype",
            ),
        ),
    ]
