# Generated by Django 4.1.1 on 2022-10-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_usertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="learningDirections",
        ),
    ]
