# Generated by Django 4.1.1 on 2022-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learningDirections", "0001_initial"),
        ("user", "0004_remove_user_learningdirections"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learningDirections",
            field=models.ManyToManyField(to="learningDirections.learningdirection"),
        ),
    ]
