# Generated by Django 4.1.1 on 2022-11-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_learningdirections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="learningDirections",
        ),
    ]
