# Generated by Django 4.1.1 on 2022-11-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_user_learningdirections"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(blank=True, default="Не указано", max_length=255),
        ),
    ]
