# Generated by Django 4.1.1 on 2022-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("topic", models.CharField(default="Тема не задана", max_length=256)),
                (
                    "methodical_material",
                    models.CharField(default="Ссылка не задана", max_length=512),
                ),
            ],
        ),
    ]
