# Generated by Django 4.1.1 on 2023-02-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("topic", models.CharField(default="Тема не задана", max_length=256)),
                (
                    "methodical_material",
                    models.CharField(default="Ссылка не задана", max_length=512),
                ),
            ],
        ),
        migrations.CreateModel(
            name="timeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(default="2023", max_length=10)),
                ("academic_hours", models.IntegerField(default=1)),
                (
                    "lessons",
                    models.ManyToManyField(blank=True, to="learningDirections.lesson"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="learningDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Не указано", max_length=50)),
                ("courseDuration", models.IntegerField(default=1)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="groups.learninggroup"
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="learningDirections.timetable",
                    ),
                ),
            ],
        ),
    ]
