# Generated by Django 4.1.1 on 2023-03-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Не указано", max_length=50, verbose_name="Название"
                    ),
                ),
                (
                    "course_duration",
                    models.IntegerField(
                        default=1, verbose_name="Длительность курса (в годах)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление обучения",
                "verbose_name_plural": "Направления обучения",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2023, verbose_name="Год")),
                ("academic_hours", models.IntegerField(default=1)),
                (
                    "learning_direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabuses",
                        to="learningDirections.learningdirection",
                        verbose_name="Направление обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "План обучения",
                "verbose_name_plural": "Планы обучения по направлениям",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="Номер урока")),
                ("name", models.CharField(default="Тема не задана", max_length=256)),
                (
                    "methodical_material",
                    models.CharField(
                        default="Ссылка не задана",
                        max_length=1024,
                        verbose_name="Ссылка на метод. материал",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics",
                        to="learningDirections.syllabus",
                        verbose_name="Учебный план",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема урока",
                "verbose_name_plural": "Темы уроков",
                "ordering": ["syllabus", "number"],
            },
        ),
    ]
