# Generated by Django 4.1.1 on 2022-10-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="learningDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Не указано", max_length=50)),
                ("courseDuration", models.IntegerField(default=1)),
            ],
        ),
    ]
