# Generated by Django 4.1.1 on 2022-11-08 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_remove_learninggroup_direction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learningDirections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningdirection",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="groups.learninggroup"
            ),
        ),
        migrations.AddField(
            model_name="learningdirection",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
