# Generated by Django 4.1.1 on 2023-03-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learningDirections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabus",
            name="learning_direction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="syllabuses",
                to="learningDirections.learningdirection",
                verbose_name="Направление обучения",
            ),
        ),
    ]
