# Generated by Django 4.1.1 on 2022-11-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
        (
            "learningDirections",
            "0002_learningdirection_groups_learningdirection_teachers",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="learningdirection",
            name="timetable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="timetable.timetable",
            ),
        ),
    ]
